# SPDX-License-Identifier: Apache-2.0
#!/usr/bin/env python3
"""Train a compact decision tree and export it as zero-dependency JavaScript.

Reads labelled features from a CSV, fits a small DecisionTreeClassifier, and
emits a single .js module exposing `MODEL_META` and `predict(features)` that
runs anywhere JavaScript runs (openvela quick apps included).

Feature order is inferred from the CSV column order, or pinned explicitly with
--feature-names. The generated file documents the order in a comment — keep the
CSV, the training call and the JS caller in the same order.

Example:
    python export_tree.py --csv features.csv --output model.js --max-depth 4
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import numpy as np
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


def read_csv(path: Path, feature_names: list[str], label_column: str):
    """Return (features, labels) arrays. Features follow `feature_names` order."""
    rows: list[list[float]] = []
    labels: list[str] = []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        missing = [name for name in [*feature_names, label_column]
                   if name not in reader.fieldnames]
        if missing:
            raise ValueError(f"CSV missing columns: {', '.join(missing)}")
        for row in reader:
            rows.append([float(row[name]) for name in feature_names])
            labels.append(row[label_column].strip())
    return np.asarray(rows, dtype=float), np.asarray(labels)


def js_number(value: float) -> str:
    return f"{value:.8g}"


def export_tree(model, feature_names: list[str], output: Path, model_name: str) -> None:
    """Recursively walk model.tree_ and emit an if/else JS predict function."""
    tree = model.tree_
    class_names = [str(value) for value in model.classes_]

    def emit_node(node: int, indent: str = "  "):
        feature_index = tree.feature[node]
        if feature_index < 0:
            counts = tree.value[node][0]
            best = int(np.argmax(counts))
            confidence = float(counts[best] / max(np.sum(counts), 1.0))
            yield f'{indent}return {{label: "{class_names[best]}", confidence: {js_number(confidence)}}}'
            return
        threshold = float(tree.threshold[node])
        yield f"{indent}if (features[{feature_index}] <= {js_number(threshold)}) {{"
        yield from emit_node(tree.children_left[node], indent + "  ")
        yield f"{indent}}} else {{"
        yield from emit_node(tree.children_right[node], indent + "  ")
        yield f"{indent}}}"

    lines = [
        "// Generated by sklearn-to-js export_tree.py. Do not edit by hand.",
        "// Feature order: " + ", ".join(feature_names),
        "",
        "export const MODEL_META = {",
        f'  name: "{model_name}",',
        f"  maxDepth: {model.get_depth()},",
        "  classes: [" + ", ".join(f'"{name}"' for name in class_names) + "],",
        f"  featureCount: {len(feature_names)}",
        "}",
        "",
        "export function predict(features) {",
        *emit_node(0),
        "}",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--label-column", default="label")
    parser.add_argument("--feature-names", default=None,
                        help="comma-separated feature order; defaults to CSV column order")
    parser.add_argument("--max-depth", type=int, default=4)
    parser.add_argument("--model-name", default="DecisionTree")
    parser.add_argument("--regression-cases", type=Path, default=None,
                        help="optional JSON file: [{vector, expected}, ...] for pre-export checks")
    args = parser.parse_args()

    if args.feature_names:
        feature_names = [n.strip() for n in args.feature_names.split(",") if n.strip()]
    else:
        with args.csv.open("r", encoding="utf-8-sig", newline="") as handle:
            feature_names = [name for name in csv.DictReader(handle).fieldnames
                             if name != args.label_column]

    features, labels = read_csv(args.csv, feature_names, args.label_column)

    x_train, x_test, y_train, y_test = train_test_split(
        features, labels, test_size=0.25, random_state=42, stratify=labels,
    )
    model = DecisionTreeClassifier(
        max_depth=args.max_depth, min_samples_leaf=10,
        class_weight="balanced", random_state=42,
    )
    model.fit(x_train, y_train)

    print(f"rows: {len(features)}, depth: {model.get_depth()}, "
          f"leaves: {model.get_n_leaves()}")
    print(classification_report(y_test, model.predict(x_test), digits=4))

    if args.regression_cases:
        cases = json.loads(args.regression_cases.read_text(encoding="utf-8"))
        for case in cases:
            vector = case["vector"]
            expected = case["expected"]
            actual = str(model.predict(np.asarray([vector], dtype=float))[0])
            if actual != expected:
                raise RuntimeError(
                    f"regression case {case.get('name', vector)} "
                    f"expected {expected!r}, got {actual!r}"
                )
            print(f"  regression {case.get('name', vector)} -> {actual}")

    export_tree(model, feature_names, args.output.resolve(), args.model_name)
    print(f"exported: {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
